version: '3.7'

services:
  primary:
    image: coredns/coredns
    volumes:
      - ./configs/primary:/config/
    ports:
     - 54:53/udp
    command: -conf /config/Corefile
    networks:
      localvpc:
        ipv4_address: 10.5.0.2

  secondary:
    image: coredns/coredns
    volumes:
      - ./configs/secondary:/config/
    ports:
     - 55:53/udp
    command: -conf /config/Corefile
    networks:
      localvpc:
        ipv4_address: 10.5.0.3

networks:
  localvpc:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
