version: '3.7'

services:
  coredns:
    image: coredns/coredns
    volumes:
      - ./config/:/config/
    ports:
     - 52:53/udp
    command: -conf /config/Corefile

    # rwasniak/work/src/github.com/miekg/coredns$ docker run -v "/Conf:/Conf" bob/coredns -conf /Conf/C
